name: ci
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit-test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        check-latest: true
        cache: true
    - name: Run Unit Tests
      run:  go test ./... -race