name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          check-latest: true
          cache: true
      - name: Install cross-compilers for linux/arm64
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser-linux.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  release-darwin-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          check-latest: true
          cache: true
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser-darwin.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}